# Generated by Django 5.0.4 on 2024-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_image',
            field=models.ImageField(upload_to='coin_images/'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], max_length=50),
        ),
    ]
