# Generated by Django 5.0.4 on 2024-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coin_coin_image_alter_coin_coin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_status',
            field=models.CharField(choices=[('select', 'Select'), ('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], max_length=50),
        ),
    ]
