# Generated by Django 4.1.13 on 2024-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0013_alter_coin_coin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_country',
            field=models.CharField(max_length=51),
        ),
    ]
