# Generated by Django 4.1.13 on 2024-04-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0017_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='created_by',
        ),
    ]
