# Generated by Django 4.1.13 on 2024-04-20 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0018_remove_coin_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_coins', to=settings.AUTH_USER_MODEL),
        ),
    ]
