# Generated by Django 4.1.13 on 2024-04-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0030_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coins.order'),
            preserve_default=False,
        ),
    ]
