# Generated by Django 4.1.13 on 2024-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_coin_coin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_status',
            field=models.CharField(choices=[('Select', 'Select'), ('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], max_length=50),
        ),
    ]
