# Generated by Django 4.1.13 on 2024-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_coin_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='created_by',
        ),
        migrations.AddField(
            model_name='coin',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
