# Generated by Django 4.1.13 on 2024-04-20 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0020_remove_coin_created_by_coin_created_by_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='created_by_id',
        ),
        migrations.AddField(
            model_name='coin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
