# Generated by Django 4.1.13 on 2024-04-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_remove_coin_created_by_coin_created_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_status',
            field=models.CharField(choices=[('Select', 'Select'), ('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], max_length=51),
        ),
    ]
