# Generated by Django 4.1.13 on 2024-04-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
