# Generated by Django 4.1.13 on 2024-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
